-- CREATE DB
IF DB_ID('TEST_DB') IS NULL
    CREATE DATABASE TEST_DB;
GO

USE TEST_DB;
GO

-- CREATE TABLE EMPLOYEE
CREATE TABLE EMPLOYEE (
    Emp_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    Emp_FirstName VARCHAR(255) NOT NULL,
    Emp_LastName VARCHAR(255) NOT NULL,
    Emp_Age INT NOT NULL,
    Emp_Building_ID INT
);
GO 

-- CREATE TABLE BUILDING
CREATE TABLE BUILDING (
    Building_ID INT NOT NULL PRIMARY KEY,
    Building_Name VARCHAR(255) NOT NULL,
    Building_Short VARCHAR(255) NOT NULL
);
GO 

-- FK
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (Emp_Building_ID)
    REFERENCES BUILDING.Building_ID;
GO



-- INSERT DATA
-- DATA INTO TABLE EMPLOYEE
INSERT INTO EMPLOYEE 
    (Emp_FirstName, Emp_LastName, Emp_Age, Emp_Building_ID)
VALUES
    ('First', 'Last', 20, 1),
    ('Harris', 'Adni', 25, 2),
    ('Haniff', 'Adni', 23, 3);
GO

SELECT * FROM EMPLOYEE;
GO

-- DATA INTO TABLE BUILDING
INSERT INTO BUILDING
    (Building_ID, Building_Name, Building_Short)
VALUES
    (1, 'Kulim 1', 'KM1'),
    (2, 'Kulim 2', 'KM2'),
    (3, 'Penang 12', 'PG12');
GO

SELECT * FROM BUILDING;
GO


-- STORED PROCEDURES
-- all Employee
CREATE PROCEDURE SP_ALL_EMPLOYEE
AS
SELECT * FROM EMPLOYEE
GO

-- Employee by Emp_ID
CREATE PROCEDURE SP_EMPLOYEE_BY_ID @Emp_ID INT
AS
SELECT * FROM EMPLOYEE
WHERE Emp_ID = @Emp_ID
GO

-- Add Employee
DROP PROCEDURE IF EXISTS SP_ADD_EMPLOYEE
GO
CREATE PROCEDURE SP_ADD_EMPLOYEE 
	@Emp_FirstName VARCHAR(128), @Emp_LastName VARCHAR(128), @Emp_Age INT, @Emp_Building_ID INT
AS
INSERT INTO EMPLOYEE 
    (Emp_FirstName, Emp_LastName, Emp_Age, Emp_Building_ID)
VALUES
    (@Emp_FirstName, @Emp_LastName, @Emp_Age, @Emp_Building_ID)
SELECT *
	FROM EMPLOYEE
	WHERE Emp_ID = SCOPE_IDENTITY()
GO

exec SP_ALL_EMPLOYEE
GO

exec SP_EMPLOYEE_BY_ID 15
GO
